# Create a GitHub Action that uses the @slack/web-api package to post a message in the Slack channel when a pull request is opened.

name: 'Slack Notification on PR'
description: 'Send a Slack notification when a pull request is opened'

inputs:
  token:
    description: 'Slack API token'
    required: true

runs:
  using: 'node16'
  main: 'index.js'

